[package]
entrypoint = "src/lib.typ"
name = "subpar"
version = "0.0.1"
compiler = "0.11.0"
authors = ["tinger <me@tinger.dev>"]
repository = "https://github.com/tingerrr/subpar"
description = "Create easily referencable subfigures."
categories = ["components", "scripting"]
keywords = ["figures", "subfigures"]
license = "MIT"
exclude = ["examples", "README.md"]

[tool.typst-test]
tests = "test"
template = "test/template.typ"
